export const shipped = [
  "zh-cn", "es", "hi", "ar", "pt", "ru", "ja", "de", "fr",
];

export const shippedKeys = [
  "initial-state", "verifying-label", "solved-label", "error-label",
  "required-label", "troubleshooting-label", "group-aria-label",
  "verify-aria-label", "verifying-aria-label", "verified-aria-label",
  "error-aria-label",
];

export const keys = [
  "initial-state", // Verify you're human
  "verifying-label", // Verifying...
  "solved-label", // You're a human
  "error-label", // Error. Try again.
  "required-label", // Please verify you're human
  "troubleshooting-label", // Troubleshoot
  "group-aria-label", // Cap verification
  "verify-aria-label", // Click to verify you're a human
  "verifying-aria-label", // Verifying you're a human, please wait
  "verified-aria-label", // We have verified you're a human, you may now continue
  "error-aria-label", // An error occurred, please try again
  "wasm-disabled", // Enable WASM for significantly faster solving
];

export const translations = {
  es: ["Verifica que eres humano","Verificando...","Eres humano","Error. Inténtalo de nuevo.","Verifica que eres humano","Solucionar problemas","Verificación de Cap","Haz clic para verificar que eres humano","Verificando que eres humano, espera","Hemos verificado que eres humano, ya puedes continuar","Se produjo un error, inténtalo de nuevo","Activa WASM para una resolución mucho más rápida"],
  pt: ["Sou humano","Verificando...","Você é humano","Erro. Tente novamente.","Verifique que você é humano","Solução de problemas","Verificação Cap","Clique para verificar que você é humano","Verificando que você é humano, aguarde","Verificamos que você é humano, você pode continuar","Ocorreu um erro, tente novamente","Ative o WASM para resolver muito mais rápido"],
  fr: ["Je suis humain","Vérification...","Vous êtes humain","Erreur. Réessayez.","Veuillez vérifier que vous êtes humain","Dépannage","Vérification Cap","Cliquez pour vérifier que vous êtes humain","Vérification que vous êtes humain, veuillez patienter","Nous avons vérifié que vous êtes humain, vous pouvez continuer","Une erreur s'est produite, veuillez réessayer","Activez WASM pour une résolution bien plus rapide"],
  de: ["Ich bin ein Mensch","Wird überprüft...","Sie sind ein Mensch","Fehler. Erneut versuchen.","Bitte bestätigen Sie, dass Sie ein Mensch sind","Fehlerbehebung","Cap-Verifizierung","Klicken, um zu bestätigen, dass Sie ein Mensch sind","Überprüfung, ob Sie ein Mensch sind, bitte warten","Wir haben bestätigt, dass Sie ein Mensch sind, Sie können fortfahren","Ein Fehler ist aufgetreten, bitte erneut versuchen","Aktivieren Sie WASM für deutlich schnelleres Lösen"],
  it: ["Verifica di essere umano","Verifica in corso...","Sei umano","Errore. Riprova.","Verifica di essere umano","Risoluzione dei problemi","Verifica Cap","Clicca per verificare di essere umano","Verifica che sei umano, attendi","Abbiamo verificato che sei umano, puoi continuare","Si è verificato un errore, riprova","Abilita WASM per una risoluzione molto più veloce"],
  nl: ["Ik ben een mens","Verifiëren...","Je bent een mens","Fout. Probeer opnieuw.","Verifieer dat je een mens bent","Problemen oplossen","Cap-verificatie","Klik om te verifiëren dat je een mens bent","Verifiëren dat je een mens bent, even geduld","We hebben geverifieerd dat je een mens bent, je kunt doorgaan","Er is een fout opgetreden, probeer opnieuw","Schakel WASM in voor veel sneller oplossen"],
  sv: ["Jag är människa","Verifierar...","Du är människa","Fel. Försök igen.","Verifiera att du är människa","Felsökning","Cap-verifiering","Klicka för att verifiera att du är människa","Verifierar att du är människa, vänta","Vi har verifierat att du är människa, du kan fortsätta","Ett fel uppstod, försök igen","Aktivera WASM för betydligt snabbare lösning"],
  da: ["Jeg er et menneske","Bekræfter...","Du er et menneske","Fejl. Prøv igen.","Bekræft, at du er et menneske","Fejlfinding","Cap-bekræftelse","Klik for at bekræfte, at du er et menneske","Bekræfter, at du er et menneske, vent","Vi har bekræftet, at du er et menneske, du kan fortsætte","Der opstod en fejl, prøv igen","Aktivér WASM for betydeligt hurtigere løsning"],
  nb: ["Jeg er et menneske","Bekrefter...","Du er et menneske","Feil. Prøv igjen.","Bekreft at du er et menneske","Feilsøking","Cap-bekreftelse","Klikk for å bekrefte at du er et menneske","Bekrefter at du er et menneske, vent","Vi har bekreftet at du er et menneske, du kan fortsette","Det oppstod en feil, prøv igjen","Aktiver WASM for betydelig raskere løsning"],
  fi: ["Vahvista, että olet ihminen","Vahvistetaan...","Olet ihminen","Virhe. Yritä uudelleen.","Vahvista, että olet ihminen","Vianmääritys","Cap-vahvistus","Napsauta vahvistaaksesi, että olet ihminen","Vahvistetaan, että olet ihminen, odota","Olemme vahvistaneet, että olet ihminen, voit jatkaa","Tapahtui virhe, yritä uudelleen","Ota WASM käyttöön huomattavasti nopeampaa ratkaisua varten"],
  pl: ["Jestem człowiekiem","Weryfikacja...","Jesteś człowiekiem","Błąd. Spróbuj ponownie.","Potwierdź, że jesteś człowiekiem","Rozwiązywanie problemów","Weryfikacja Cap","Kliknij, aby potwierdzić, że jesteś człowiekiem","Weryfikacja, że jesteś człowiekiem, czekaj","Potwierdziliśmy, że jesteś człowiekiem, możesz kontynuować","Wystąpił błąd, spróbuj ponownie","Włącz WASM, aby rozwiązywać znacznie szybciej"],
  cs: ["Ověřte, že jste člověk","Ověřování...","Jste člověk","Chyba. Zkuste to znovu.","Ověřte, že jste člověk","Řešení potíží","Ověření Cap","Kliknutím ověřte, že jste člověk","Ověřujeme, že jste člověk, čekejte","Ověřili jsme, že jste člověk, můžete pokračovat","Došlo k chybě, zkuste to znovu","Povolte WASM pro výrazně rychlejší řešení"],
  sk: ["Overte, že ste človek","Overovanie...","Ste človek","Chyba. Skúste znova.","Overte, že ste človek","Riešenie problémov","Overenie Cap","Kliknutím overte, že ste človek","Overujeme, že ste človek, čakajte","Overili sme, že ste človek, môžete pokračovať","Vyskytla sa chyba, skúste znova","Povoľte WASM pre výrazne rýchlejšie riešenie"],
  ru: ["Я человек","Проверка...","Вы человек","Ошибка. Повторите.","Подтвердите, что вы человек","Устранение неполадок","Проверка Cap","Нажмите, чтобы подтвердить, что вы человек","Проверяем, что вы человек, подождите","Мы подтвердили, что вы человек, можете продолжить","Произошла ошибка, повторите попытку","Включите WASM для значительно более быстрого решения"],
  uk: ["Я людина","Перевірка...","Ви людина","Помилка. Спробуйте.","Підтвердьте, що ви людина","Усунення несправностей","Перевірка Cap","Натисніть, щоб підтвердити, що ви людина","Перевіряємо, що ви людина, зачекайте","Ми підтвердили, що ви людина, можете продовжити","Сталася помилка, спробуйте ще раз","Увімкніть WASM для значно швидшого розв’язання"],
  ca: ["Verifica que ets humà","Verificant...","Ets humà","Error. Torna-ho a provar.","Verifica que ets humà","Resolució de problemes","Verificació de Cap","Fes clic per verificar que ets humà","Verificant que ets humà, espera","Hem verificat que ets humà, ja pots continuar","S'ha produït un error, torna-ho a provar","Activa WASM per resoldre molt més ràpid"],
  gl: ["Verifica que es humano","Verificando...","Es humano","Erro. Téntao de novo.","Verifica que es humano","Resolución de problemas","Verificación de Cap","Fai clic para verificar que es humano","Verificando que es humano, agarda","Verificamos que es humano, xa podes continuar","Produciuse un erro, téntao de novo","Activa WASM para resolver moito máis rápido"],
  af: ["Bevestig dat jy 'n mens is","Verifieer tans...","Jy is 'n mens","Fout. Probeer weer.","Bevestig asseblief dat jy 'n mens is","Probleemoplossing","Cap-verifikasie","Klik om te bevestig dat jy 'n mens is","Bevestig tans dat jy 'n mens is, wag asseblief","Ons het bevestig dat jy 'n mens is, jy kan voortgaan","'n Fout het voorgekom, probeer weer","Aktiveer WASM vir aansienlik vinniger oplossing"],
  id: ["Verifikasi Anda manusia","Memverifikasi...","Anda manusia","Kesalahan. Coba lagi.","Harap verifikasi Anda manusia","Pemecahan masalah","Verifikasi Cap","Klik untuk memverifikasi Anda manusia","Memverifikasi Anda manusia, harap tunggu","Kami telah memverifikasi Anda manusia, Anda dapat melanjutkan","Terjadi kesalahan, coba lagi","Aktifkan WASM untuk penyelesaian yang jauh lebih cepat"],
  ms: ["Sahkan anda manusia","Mengesahkan...","Anda manusia","Ralat. Cuba lagi.","Sila sahkan anda manusia","Penyelesaian masalah","Pengesahan Cap","Klik untuk mengesahkan anda manusia","Mengesahkan anda manusia, sila tunggu","Kami telah mengesahkan anda manusia, anda boleh teruskan","Ralat berlaku, sila cuba lagi","Dayakan WASM untuk penyelesaian yang jauh lebih pantas"],
  ro: ["Verificați că sunteți om","Se verifică...","Sunteți om","Eroare. Încercați din nou.","Verificați că sunteți om","Depanare","Verificare Cap","Faceți clic pentru a verifica că sunteți om","Verificăm că sunteți om, așteptați","Am verificat că sunteți om, puteți continua","A apărut o eroare, încercați din nou","Activați WASM pentru o rezolvare mult mai rapidă"],
  hu: ["Igazolja, hogy ember","Ellenőrzés...","Ön ember","Hiba. Próbálja újra.","Igazolja, hogy ember","Hibaelhárítás","Cap-ellenőrzés","Kattintson az emberi voltának igazolásához","Ellenőrizzük, hogy ember-e, kérjük várjon","Igazoltuk, hogy ember, folytathatja","Hiba történt, próbálja újra","Engedélyezze a WASM-ot a sokkal gyorsabb megoldásért"],
  el: ["Είμαι άνθρωπος","Επαλήθευση...","Είστε άνθρωπος","Σφάλμα. Δοκιμάστε ξανά.","Επιβεβαιώστε ότι είστε άνθρωπος","Αντιμετώπιση προβλημάτων","Επαλήθευση Cap","Κάντε κλικ για να επιβεβαιώσετε ότι είστε άνθρωπος","Επαληθεύουμε ότι είστε άνθρωπος, περιμένετε","Επιβεβαιώσαμε ότι είστε άνθρωπος, μπορείτε να συνεχίσετε","Παρουσιάστηκε σφάλμα, δοκιμάστε ξανά","Ενεργοποιήστε το WASM για πολύ ταχύτερη επίλυση"],
  bg: ["Потвърдете, че сте човек","Проверка...","Вие сте човек","Грешка. Опитайте пак.","Потвърдете, че сте човек","Отстраняване на неизправности","Проверка Cap","Щракнете, за да потвърдите, че сте човек","Проверяваме, че сте човек, изчакайте","Потвърдихме, че сте човек, можете да продължите","Възникна грешка, опитайте отново","Активирайте WASM за значително по-бързо решаване"],
  sr: ["Потврдите да сте човек","Провера...","Ви сте човек","Грешка. Покушајте опет.","Потврдите да сте човек","Решавање проблема","Cap провера","Кликните да потврдите да сте човек","Проверавамо да сте човек, сачекајте","Потврдили смо да сте човек, можете наставити","Дошло је до грешке, покушајте поново","Омогућите WASM за знатно брже решавање"],
  hr: ["Potvrdite da ste čovjek","Provjera...","Vi ste čovjek","Greška. Pokušajte opet.","Potvrdite da ste čovjek","Rješavanje problema","Cap provjera","Kliknite da potvrdite da ste čovjek","Provjeravamo da ste čovjek, pričekajte","Potvrdili smo da ste čovjek, možete nastaviti","Došlo je do pogreške, pokušajte ponovno","Omogućite WASM za znatno brže rješavanje"],
  sl: ["Potrdite, da ste človek","Preverjanje...","Ste človek","Napaka. Poskusite znova.","Potrdite, da ste človek","Odpravljanje težav","Preverjanje Cap","Kliknite za potrditev, da ste človek","Preverjamo, da ste človek, počakajte","Potrdili smo, da ste človek, lahko nadaljujete","Prišlo je do napake, poskusite znova","Omogočite WASM za bistveno hitrejše reševanje"],
  et: ["Kinnitage, et olete inimene","Kontrollimine...","Olete inimene","Viga. Proovige uuesti.","Kinnitage, et olete inimene","Tõrkeotsing","Cap kontroll","Klõpsake, et kinnitada, et olete inimene","Kontrollime, et olete inimene, oodake","Kinnitasime, et olete inimene, võite jätkata","Ilmnes viga, proovige uuesti","Lubage WASM oluliselt kiiremaks lahendamiseks"],
  lv: ["Esmu cilvēks","Pārbauda...","Jūs esat cilvēks","Kļūda. Mēģiniet vēlreiz.","Apstipriniet, ka esat cilvēks","Problēmu novēršana","Cap pārbaude","Noklikšķiniet, lai apstiprinātu, ka esat cilvēks","Pārbaudām, ka esat cilvēks, uzgaidiet","Mēs apstiprinājām, ka esat cilvēks, varat turpināt","Radās kļūda, mēģiniet vēlreiz","Iespējojiet WASM ievērojami ātrākai risināšanai"],
  lt: ["Esu žmogus","Tikrinama...","Jūs esate žmogus","Klaida. Bandykite vėl.","Patvirtinkite, kad esate žmogus","Trikčių šalinimas","Cap patvirtinimas","Spustelėkite, kad patvirtintumėte, jog esate žmogus","Tikriname, ar esate žmogus, palaukite","Patvirtinome, kad esate žmogus, galite tęsti","Įvyko klaida, bandykite dar kartą","Įjunkite WASM, kad išspręstumėte daug greičiau"],
  tr: ["Ben insanım","Doğrulanıyor...","İnsansınız","Hata. Tekrar deneyin.","Lütfen insan olduğunuzu doğrulayın","Sorun giderme","Cap doğrulaması","İnsan olduğunuzu doğrulamak için tıklayın","İnsan olduğunuz doğrulanıyor, lütfen bekleyin","İnsan olduğunuzu doğruladık, devam edebilirsiniz","Bir hata oluştu, tekrar deneyin","Çok daha hızlı çözüm için WASM'ı etkinleştirin"],
  vi: ["Xác minh bạn là con người","Đang xác minh...","Bạn là con người","Lỗi. Thử lại.","Vui lòng xác minh bạn là con người","Khắc phục sự cố","Xác minh Cap","Nhấp để xác minh bạn là con người","Đang xác minh bạn là con người, vui lòng đợi","Chúng tôi đã xác minh bạn là con người, bạn có thể tiếp tục","Đã xảy ra lỗi, vui lòng thử lại","Bật WASM để giải nhanh hơn đáng kể"],
  tl: ["Patunayan na ikaw ay tao","Bineberipika...","Ikaw ay tao","Error. Subukan ulit.","Pakipatunayan na ikaw ay tao","Pag-troubleshoot","Pagpapatunay ng Cap","I-click para patunayan na ikaw ay tao","Pinapatunayan na ikaw ay tao, maghintay","Napatunayan namin na ikaw ay tao, maaari nang magpatuloy","May naganap na error, subukan ulit","I-enable ang WASM para sa mas mabilis na paglutas"],
  ar: ["تحقق من أنك إنسان","جارٍ التحقق...","أنت إنسان","خطأ. حاول مرة أخرى.","يرجى التحقق من أنك إنسان","استكشاف الأخطاء وإصلاحها","تحقق Cap","انقر للتحقق من أنك إنسان","جارٍ التحقق من أنك إنسان، يرجى الانتظار","لقد تحققنا من أنك إنسان، يمكنك المتابعة الآن","حدث خطأ، يرجى المحاولة مرة أخرى","فعّل WASM لحل أسرع بكثير"],
  he: ["אמת שאתה אנושי","מאמת...","אתה אנושי","שגיאה. נסה שוב.","נא לאמת שאתה אנושי","פתרון בעיות","אימות Cap","לחץ כדי לאמת שאתה אנושי","מאמת שאתה אנושי, אנא המתן","אימתנו שאתה אנושי, אפשר להמשיך","אירעה שגיאה, נסה שוב","הפעל את WASM לפתרון מהיר בהרבה"],
  fa: ["تأیید کنید که انسان هستید","در حال تأیید...","شما انسان هستید","خطا. دوباره تلاش کنید.","لطفاً تأیید کنید که انسان هستید","عیب‌یابی","تأیید Cap","برای تأیید اینکه انسان هستید کلیک کنید","در حال تأیید اینکه انسان هستید، لطفاً صبر کنید","تأیید کردیم که انسان هستید، می‌توانید ادامه دهید","خطایی رخ داد، دوباره تلاش کنید","برای حل بسیار سریع‌تر، WASM را فعال کنید"],
  "zh-cn": ["确认你是真人","正在验证...","你是真人","出错了。请重试。","请确认你是真人","故障排除","Cap 验证","点击以确认你是真人","正在验证你是真人，请稍候","我们已确认你是真人，你可以继续了","发生错误，请重试","启用 WASM 可大幅加快求解速度"],
  "zh-tw": ["確認你是真人","正在驗證...","你是真人","發生錯誤。請重試。","請確認你是真人","疑難排解","Cap 驗證","點擊以確認你是真人","正在驗證你是真人，請稍候","我們已確認你是真人，你可以繼續了","發生錯誤，請重試","啟用 WASM 可大幅加快解算速度"],
  ja: ["私は人間です","確認中...","あなたは人間です","エラー。再試行を。","あなたが人間であることを確認してください","トラブルシューティング","Cap 認証","クリックして人間であることを確認","あなたが人間であることを確認しています。お待ちください","あなたが人間であることを確認しました。続行できます","エラーが発生しました。もう一度お試しください","WASM を有効にすると大幅に高速化されます"],
  ko: ["사람인지 확인하세요","확인 중...","당신은 사람입니다","오류. 다시 시도하세요.","사람인지 확인해 주세요","문제 해결","Cap 인증","클릭하여 사람인지 확인하세요","사람인지 확인 중입니다. 잠시 기다려 주세요","사람임을 확인했습니다. 계속할 수 있습니다","오류가 발생했습니다. 다시 시도하세요","훨씬 빠른 처리를 위해 WASM을 활성화하세요"],
  az: ["Mən insanam","Yoxlanılır...","Siz insansınız","Xəta. Yenidən cəhd edin.","İnsan olduğunuzu təsdiqləyin","Problemlərin həlli","Cap yoxlaması","İnsan olduğunuzu təsdiqləmək üçün klikləyin","İnsan olduğunuz yoxlanılır, gözləyin","İnsan olduğunuzu təsdiqlədik, davam edə bilərsiniz","Xəta baş verdi, yenidən cəhd edin","Daha sürətli həll üçün WASM-ı aktivləşdirin"],
  kk: ["Адам екеніңізді растаңыз","Тексерілуде...","Сіз адамсыз","Қате. Қайталап көріңіз.","Адам екеніңізді растаңыз","Ақаулықтарды жою","Cap растауы","Адам екеніңізді растау үшін басыңыз","Адам екеніңізді тексерудеміз, күтіңіз","Адам екеніңізді растадық, жалғастыра аласыз","Қате орын алды, қайталап көріңіз","Әлдеқайда жылдам шешу үшін WASM қосыңыз"],
  ka: ["მე ადამიანი ვარ","მოწმდება...","თქვენ ადამიანი ხართ","შეცდომა. სცადეთ.","დაადასტურეთ, რომ ადამიანი ხართ","პრობლემის გადაჭრა","Cap-ის დადასტურება","დააწკაპუნეთ, რომ დაადასტუროთ, რომ ადამიანი ხართ","ვამოწმებთ, რომ ადამიანი ხართ, დაელოდეთ","დავადასტურეთ, რომ ადამიანი ხართ, შეგიძლიათ გააგრძელოთ","მოხდა შეცდომა, სცადეთ ხელახლა","ჩართეთ WASM მნიშვნელოვნად სწრაფი ამოხსნისთვის"],
  hy: ["Հաստատեք, որ մարդ եք","Ստուգվում է...","Դուք մարդ եք","Սխալ. Կրկին փորձեք։","Հաստատեք, որ մարդ եք","Անսարքությունների վերացում","Cap ստուգում","Սեղմեք՝ հաստատելու, որ մարդ եք","Ստուգում ենք, որ մարդ եք, սպասեք","Մենք հաստատեցինք, որ մարդ եք, կարող եք շարունակել","Սխալ տեղի ունեցավ, կրկին փորձեք","Միացրեք WASM-ը զգալիորեն ավելի արագ լուծման համար"],
  ur: ["تصدیق کریں کہ آپ انسان ہیں","تصدیق ہو رہی ہے...","آپ انسان ہیں","خرابی۔ دوبارہ کوشش کریں۔","براہ کرم تصدیق کریں کہ آپ انسان ہیں","مسئلہ حل کریں","Cap تصدیق","تصدیق کے لیے کلک کریں کہ آپ انسان ہیں","تصدیق ہو رہی ہے کہ آپ انسان ہیں، انتظار کریں","ہم نے تصدیق کر لی کہ آپ انسان ہیں، اب آپ جاری رکھ سکتے ہیں","ایک خرابی پیش آئی، دوبارہ کوشش کریں","نمایاں طور پر تیز حل کے لیے WASM فعال کریں"],
  hi: ["पुष्टि करें कि आप मानव हैं","सत्यापित हो रहा है...","आप मानव हैं","त्रुटि। पुनः प्रयास करें।","कृपया पुष्टि करें कि आप मानव हैं","समस्या निवारण","Cap सत्यापन","पुष्टि करने के लिए क्लिक करें कि आप मानव हैं","सत्यापित किया जा रहा है कि आप मानव हैं, प्रतीक्षा करें","हमने पुष्टि कर दी है कि आप मानव हैं, अब आप जारी रख सकते हैं","एक त्रुटि हुई, पुनः प्रयास करें","काफी तेज़ समाधान के लिए WASM सक्षम करें"],
  bn: ["আপনি মানুষ তা যাচাই করুন","যাচাই করা হচ্ছে...","আপনি মানুষ","ত্রুটি। আবার চেষ্টা করুন।","অনুগ্রহ করে যাচাই করুন যে আপনি মানুষ","সমস্যা সমাধান","Cap যাচাই","আপনি মানুষ তা যাচাই করতে ক্লিক করুন","আপনি মানুষ তা যাচাই করা হচ্ছে, অপেক্ষা করুন","আমরা যাচাই করেছি যে আপনি মানুষ, এখন চালিয়ে যেতে পারেন","একটি ত্রুটি ঘটেছে, আবার চেষ্টা করুন","অনেক দ্রুত সমাধানের জন্য WASM সক্ষম করুন"],
  ta: ["நான் மனிதர்","சரிபார்க்கிறது...","நீங்கள் மனிதர்","பிழை. மீண்டும் முயலவும்.","நீங்கள் மனிதர் என்பதை உறுதிப்படுத்தவும்","சிக்கல் தீர்வு","Cap சரிபார்ப்பு","நீங்கள் மனிதர் என உறுதிப்படுத்த கிளிக் செய்யவும்","நீங்கள் மனிதர் என சரிபார்க்கிறது, காத்திருக்கவும்","நீங்கள் மனிதர் என உறுதிப்படுத்தினோம், தொடரலாம்","பிழை ஏற்பட்டது, மீண்டும் முயற்சிக்கவும்","மிக வேகமான தீர்வுக்கு WASM ஐ இயக்கவும்"],
  te: ["నేను మనిషిని","ధృవీకరిస్తోంది...","మీరు మనిషి","లోపం. మళ్లీ ప్రయత్నించండి.","దయచేసి మీరు మనిషి అని ధృవీకరించండి","సమస్య పరిష్కారం","Cap ధృవీకరణ","మీరు మనిషి అని ధృవీకరించడానికి క్లిక్ చేయండి","మీరు మనిషి అని ధృవీకరిస్తోంది, వేచి ఉండండి","మీరు మనిషి అని మేము ధృవీకరించాము, ఇప్పుడు కొనసాగవచ్చు","లోపం సంభవించింది, మళ్లీ ప్రయత్నించండి","చాలా వేగవంతమైన పరిష్కారం కోసం WASM ప్రారంభించండి"],
  mr: ["मी मानव आहे","पडताळणी होत आहे...","तुम्ही मानव आहात","त्रुटी. पुन्हा प्रयत्न करा.","कृपया तुम्ही मानव आहात याची पुष्टी करा","समस्यानिवारण","Cap पडताळणी","तुम्ही मानव आहात याची पुष्टी करण्यासाठी क्लिक करा","तुम्ही मानव आहात याची पडताळणी होत आहे, प्रतीक्षा करा","आम्ही पुष्टी केली की तुम्ही मानव आहात, आता पुढे जाऊ शकता","त्रुटी आली, पुन्हा प्रयत्न करा","खूप जलद सोडवण्यासाठी WASM सक्षम करा"],
  gu: ["તમે માનવ છો તેની ખાતરી કરો","ચકાસણી થઈ રહી છે...","તમે માનવ છો","ભૂલ. ફરી પ્રયાસ કરો.","કૃપા કરીને ખાતરી કરો કે તમે માનવ છો","સમસ્યાનિવારણ","Cap ચકાસણી","તમે માનવ છો તેની ખાતરી કરવા ક્લિક કરો","તમે માનવ છો તેની ચકાસણી થઈ રહી છે, રાહ જુઓ","અમે ખાતરી કરી કે તમે માનવ છો, હવે ચાલુ રાખી શકો છો","ભૂલ આવી, ફરી પ્રયાસ કરો","ઘણા ઝડપી ઉકેલ માટે WASM સક્ષમ કરો"],
  kn: ["ನಾನು ಮನುಷ್ಯ","ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...","ನೀವು ಮನುಷ್ಯ","ದೋಷ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.","ದಯವಿಟ್ಟು ನೀವು ಮನುಷ್ಯ ಎಂದು ದೃಢೀಕರಿಸಿ","ಸಮಸ್ಯೆ ಪರಿಹಾರ","Cap ಪರಿಶೀಲನೆ","ನೀವು ಮನುಷ್ಯ ಎಂದು ದೃಢೀಕರಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ","ನೀವು ಮನುಷ್ಯ ಎಂದು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ, ನಿರೀಕ್ಷಿಸಿ","ನೀವು ಮನುಷ್ಯ ಎಂದು ದೃಢೀಕರಿಸಿದ್ದೇವೆ, ಮುಂದುವರಿಯಬಹುದು","ದೋಷ ಸಂಭವಿಸಿದೆ, ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ","ಬಹಳ ವೇಗದ ಪರಿಹಾರಕ್ಕಾಗಿ WASM ಸಕ್ರಿಯಗೊಳಿಸಿ"],
  ml: ["ഞാൻ മനുഷ്യനാണ്","പരിശോധിക്കുന്നു...","നിങ്ങൾ മനുഷ്യനാണ്","പിശക്. വീണ്ടും ശ്രമിക്കുക.","ദയവായി നിങ്ങൾ മനുഷ്യനാണെന്ന് സ്ഥിരീകരിക്കുക","പ്രശ്നപരിഹാരം","Cap പരിശോധന","നിങ്ങൾ മനുഷ്യനാണെന്ന് സ്ഥിരീകരിക്കാൻ ക്ലിക്ക് ചെയ്യുക","നിങ്ങൾ മനുഷ്യനാണെന്ന് പരിശോധിക്കുന്നു, കാത്തിരിക്കുക","നിങ്ങൾ മനുഷ്യനാണെന്ന് ഞങ്ങൾ സ്ഥിരീകരിച്ചു, തുടരാം","ഒരു പിശക് സംഭവിച്ചു, വീണ്ടും ശ്രമിക്കുക","വളരെ വേഗത്തിലുള്ള പരിഹാരത്തിന് WASM പ്രവർത്തനക്ഷമമാക്കുക"],
  pa: ["ਪੁਸ਼ਟੀ ਕਰੋ ਕਿ ਤੁਸੀਂ ਮਨੁੱਖ ਹੋ","ਪੁਸ਼ਟੀ ਹੋ ਰਹੀ ਹੈ...","ਤੁਸੀਂ ਮਨੁੱਖ ਹੋ","ਗਲਤੀ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।","ਕਿਰਪਾ ਕਰਕੇ ਪੁਸ਼ਟੀ ਕਰੋ ਕਿ ਤੁਸੀਂ ਮਨੁੱਖ ਹੋ","ਸਮੱਸਿਆ ਹੱਲ","Cap ਪੁਸ਼ਟੀ","ਪੁਸ਼ਟੀ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ ਕਿ ਤੁਸੀਂ ਮਨੁੱਖ ਹੋ","ਪੁਸ਼ਟੀ ਹੋ ਰਹੀ ਹੈ ਕਿ ਤੁਸੀਂ ਮਨੁੱਖ ਹੋ, ਉਡੀਕ ਕਰੋ","ਅਸੀਂ ਪੁਸ਼ਟੀ ਕਰ ਲਈ ਹੈ ਕਿ ਤੁਸੀਂ ਮਨੁੱਖ ਹੋ, ਹੁਣ ਜਾਰੀ ਰੱਖ ਸਕਦੇ ਹੋ","ਇੱਕ ਗਲਤੀ ਆਈ, ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ","ਬਹੁਤ ਤੇਜ਼ ਹੱਲ ਲਈ WASM ਚਾਲੂ ਕਰੋ"],
  th: ["ยืนยันว่าคุณเป็นมนุษย์","กำลังยืนยัน...","คุณเป็นมนุษย์","ข้อผิดพลาด ลองอีกครั้ง","โปรดยืนยันว่าคุณเป็นมนุษย์","การแก้ไขปัญหา","การยืนยัน Cap","คลิกเพื่อยืนยันว่าคุณเป็นมนุษย์","กำลังยืนยันว่าคุณเป็นมนุษย์ โปรดรอ","เรายืนยันแล้วว่าคุณเป็นมนุษย์ คุณดำเนินการต่อได้","เกิดข้อผิดพลาด โปรดลองอีกครั้ง","เปิดใช้งาน WASM เพื่อการแก้ปัญหาที่เร็วขึ้นมาก"],
  sw: ["Mimi ni binadamu","Inathibitisha...","Wewe ni binadamu","Hitilafu. Jaribu tena.","Tafadhali thibitisha kuwa wewe ni binadamu","Utatuzi wa matatizo","Uthibitisho wa Cap","Bofya ili kuthibitisha kuwa wewe ni binadamu","Inathibitisha kuwa wewe ni binadamu, tafadhali subiri","Tumethibitisha kuwa wewe ni binadamu, unaweza kuendelea","Hitilafu imetokea, tafadhali jaribu tena","Washa WASM kwa utatuzi wa haraka zaidi"],
  am: ["ሰው መሆንዎን ያረጋግጡ","በማረጋገጥ ላይ...","እርስዎ ሰው ነዎት","ስህተት። እንደገና ይሞክሩ።","እባክዎ ሰው መሆንዎን ያረጋግጡ","ችግር መፍታት","የCap ማረጋገጫ","ሰው መሆንዎን ለማረጋገጥ ጠቅ ያድርጉ","ሰው መሆንዎን በማረጋገጥ ላይ፣ እባክዎ ይጠብቁ","ሰው መሆንዎን አረጋግጠናል፣ መቀጠል ይችላሉ","ስህተት ተከስቷል፣ እባክዎ እንደገና ይሞክሩ","በጣም ፈጣን መፍትሄ ለማግኘት WASM ን ያንቁ"],
  my: ["ကျွန်ုပ် လူသားဖြစ်သည်","အတည်ပြုနေသည်...","သင်သည် လူသားဖြစ်သည်","အမှား။ ထပ်ကြိုးစားပါ။","သင်သည် လူသားဖြစ်ကြောင်း အတည်ပြုပါ","ပြဿနာဖြေရှင်းခြင်း","Cap အတည်ပြုခြင်း","သင်သည် လူသားဖြစ်ကြောင်း အတည်ပြုရန် နှိပ်ပါ","သင်သည် လူသားဖြစ်ကြောင်း အတည်ပြုနေသည်၊ စောင့်ပါ","သင်သည် လူသားဖြစ်ကြောင်း ကျွန်ုပ်တို့ အတည်ပြုပြီးပါပြီ၊ ဆက်လက်လုပ်ဆောင်နိုင်ပါသည်","အမှားဖြစ်ပွားခဲ့သည်၊ ထပ်ကြိုးစားပါ","များစွာပိုမြန်သော ဖြေရှင်းမှုအတွက် WASM ကိုဖွင့်ပါ"],
  km: ["បញ្ជាក់ថាអ្នកជាមនុស្ស","កំពុងផ្ទៀងផ្ទាត់...","អ្នកជាមនុស្ស","កំហុស។ សាកល្បងម្តងទៀត។","សូមបញ្ជាក់ថាអ្នកជាមនុស្ស","ការដោះស្រាយបញ្ហា","ការផ្ទៀងផ្ទាត់ Cap","ចុចដើម្បីបញ្ជាក់ថាអ្នកជាមនុស្ស","កំពុងផ្ទៀងផ្ទាត់ថាអ្នកជាមនុស្ស សូមរង់ចាំ","យើងបានផ្ទៀងផ្ទាត់ថាអ្នកជាមនុស្ស អ្នកអាចបន្តបាន","មានកំហុសកើតឡើង សូមសាកល្បងម្តងទៀត","បើក WASM សម្រាប់ការដោះស្រាយលឿនជាងមុនច្រើន"],
};
