import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const wasmPath = join(root, "vendor", "hashwx.wasm");
const outPath = join(root, "src", "hashwx-wasm.js");
const commit = readFileSync(join(root, "vendor", "hashwx-COMMIT.txt"), "utf8").trim();

const wasm = readFileSync(wasmPath);
const digest = createHash("sha256").update(wasm).digest("hex");
const b64 = wasm.toString("base64");

const chunks = [];
for (let i = 0; i < b64.length; i += 96) chunks.push(`  "${b64.slice(i, i + 96)}"`);

writeFileSync(
  outPath,
  `// Generated by scripts/vendor-hashwx.mjs. Do not edit.
// Source: https://github.com/tevador/hashwx @ ${commit}
// Built with emcc, lowered to WebAssembly 1.0 (MVP).
// sha256: ${digest}
// bytes:  ${wasm.length}

export const HASHWX_WASM_SHA256 =
  "${digest}";

export const HASHWX_WASM_BASE64 =
${chunks.join(" +\n")};
`,
);

console.log(`wrote ${outPath}`);
console.log(`  source commit ${commit}`);
console.log(`  wasm ${wasm.length} bytes, sha256 ${digest}`);
console.log(`  base64 ${b64.length} chars`);
